
// This is an autogenerated file from Firebase Studio.
'use client'; 

import { useEffect, useState, useTransition } from 'react';
import Link from 'next/link';
import type { Story } from '@/lib/types';
import { getStories, updateStory as dbUpdateStory } from '@/lib/mock-db'; 
import { AdminStoryControls } from '@/components/admin/AdminStoryControls';
import { GenerateStorySection } from '@/components/admin/GenerateStorySection';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Loader2, AlertTriangle, Inbox, CalendarCog, Repeat, Info, CheckCircle, ShieldQuestion } from 'lucide-react';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { parseISO, isValid } from 'date-fns';

export default function AdminPage() {
  const [stories, setStories] = useState<Story[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isRefreshing, startRefreshTransition] = useTransition();
  const { toast } = useToast();
  const [autoPublicationAttempted, setAutoPublicationAttempted] = useState(false);

  const fetchStories = async (isManualRefresh = false) => {
    if(!isManualRefresh && !isLoading) setIsLoading(true); // Show loading only if not already loading
    setError(null);
    console.log('[AdminPage Fetch] Fetching stories. ManualRefresh:', isManualRefresh);
    try {
      let fetchedStories = await getStories();
      console.log('[AdminPage Fetch] Fetched stories count:', fetchedStories.length);
      
      // Automatic Publication Check
      if (!autoPublicationAttempted || isManualRefresh) {
        const now = new Date();
        let publishedCount = 0;
        const storiesToUpdatePromises: Promise<Story | undefined>[] = [];

        fetchedStories
          .filter(story => 
            story.status === 'pending' && 
            story.scheduledAtDate && 
            story.scheduledAtTime
          )
          .filter(story => {
            try {
              const scheduledDateTime = parseISO(`${story.scheduledAtDate}T${story.scheduledAtTime}`);
              return isValid(scheduledDateTime) && scheduledDateTime <= now;
            } catch(e) {
              console.error('[AdminPage AutoPublish] Error parsing schedule for story:', story.id, e);
              return false;
            }
          })
          .forEach(story => {
            publishedCount++;
            console.log('[AdminPage AutoPublish] Marking story for auto-publication:', story.id, story.title);
            storiesToUpdatePromises.push(dbUpdateStory(story.id, {
              status: 'published',
              publishedAt: now.toISOString(),
              scheduledAtDate: undefined, 
              scheduledAtTime: undefined,
            }));
          });

        if (storiesToUpdatePromises.length > 0) {
          if (isManualRefresh || !autoPublicationAttempted) { // Show toast on manual refresh or first auto attempt
             toast({
                title: "Otomatik Yayın Kontrolü",
                description: `${storiesToUpdatePromises.length} adet zamanı gelmiş hikaye yayınlanıyor...`
            });
          }
          await Promise.all(storiesToUpdatePromises);
          fetchedStories = await getStories(); // Re-fetch after updates
           if (publishedCount > 0 && (isManualRefresh || !autoPublicationAttempted)) { 
            toast({
                variant: "default",
                title: "Hikayeler Otomatik Yayınlandı",
                description: `${publishedCount} hikaye başarıyla yayınlandı.`,
                action: <CheckCircle className="text-green-500" />,
            });
           }
        }
        if (!autoPublicationAttempted) {
            setAutoPublicationAttempted(true);
            console.log('[AdminPage AutoPublish] Auto publication check complete on load.');
        }
      }

      fetchedStories.sort((a, b) => {
        // Sort by status: awaiting_approval -> pending -> published
        const statusOrder = { 'awaiting_approval': 1, 'pending': 2, 'published': 3 };
        if (statusOrder[a.status] !== statusOrder[b.status]) {
          return statusOrder[a.status] - statusOrder[b.status];
        }
        
        // Within 'pending', sort by scheduledAtDate (earliest first)
        if (a.status === 'pending' && b.status === 'pending') {
          if (a.scheduledAtDate && b.scheduledAtDate) {
            try {
                const dateA = parseISO(`${a.scheduledAtDate}T${a.scheduledAtTime || '00:00'}`);
                const dateB = parseISO(`${b.scheduledAtDate}T${b.scheduledAtTime || '00:00'}`);
                if (isValid(dateA) && isValid(dateB) && dateA.getTime() !== dateB.getTime()) {
                    return dateA.getTime() - dateB.getTime();
                }
            } catch (e) { /* ignore sort error for invalid dates */ }
          } else if (a.scheduledAtDate) {
            return -1; 
          } else if (b.scheduledAtDate) {
            return 1;  
          }
        }
        // Default sort by createdAt (newest first)
        try {
            const dateA = parseISO(a.createdAt);
            const dateB = parseISO(b.createdAt);
            if(isValid(dateA) && isValid(dateB)) return dateB.getTime() - dateA.getTime();
        } catch (e) { /* ignore sort error for invalid dates */ }
        return 0;
      });
      setStories(fetchedStories);
      console.log('[AdminPage Fetch] Stories set to state. Count:', fetchedStories.length);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Hikayeler yüklenemedi.');
      console.error('[AdminPage Fetch] Error fetching stories:', e);
    } finally {
      if(isLoading) setIsLoading(false);
    }
  };

  useEffect(() => {
    console.log('[AdminPage UseEffect] Initial fetch triggered.');
    fetchStories(false); 
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleStoryGeneratedOrUpdated = () => {
    console.log('[AdminPage Callback] Story generated or updated. Refreshing list.');
    startRefreshTransition(() => {
      fetchStories(true); 
    });
  };
  
  const awaitingApprovalStories = stories.filter(s => s.status === 'awaiting_approval');
  const pendingStories = stories.filter(s => s.status === 'pending');
  const publishedStories = stories.filter(s => s.status === 'published');

  if (isLoading && stories.length === 0) {
    return (
      <div className="flex justify-center items-center min-h-[calc(100vh-200px)]">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
        <p className="ml-4 text-lg text-muted-foreground">Hikayeler yükleniyor ve kontrol ediliyor...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-10 text-red-600 bg-red-50 p-6 rounded-lg shadow-md">
        <AlertTriangle className="mx-auto h-12 w-12 mb-4" />
        <h2 className="text-2xl font-semibold mb-2">Hikayeler Yüklenirken Hata Oluştu</h2>
        <p>{error}</p>
        <button onClick={() => fetchStories(true)} className="mt-4 px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700">
          Tekrar Dene
        </button>
      </div>
    );
  }
  
  const renderStoryList = (storyList: Story[], listTitle: string) => {
    if (storyList.length === 0) {
      return (
        <div className="text-center py-10 text-muted-foreground bg-card p-6 rounded-lg shadow">
          <Inbox className="mx-auto h-12 w-12 mb-4" />
          <p className="text-lg">Şu anda hiç {listTitle.toLowerCase()} hikaye yok.</p>
        </div>
      );
    }
    return (
      <div className="space-y-6">
        {storyList.map(story => (
          <AdminStoryControls 
            key={story.id} 
            story={story} 
            onStoryUpdate={handleStoryGeneratedOrUpdated}
          />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
        <h1 className="text-3xl md:text-4xl font-bold text-foreground tracking-tight">Hikaye Yönetimi</h1>
        <div className="flex gap-2 flex-wrap">
          <Button asChild variant="outline">
            <Link href="/admin/scheduling">
              <CalendarCog className="mr-2 h-5 w-5" />
              Tarih Bazlı Planlama
            </Link>
          </Button>
          <Button asChild variant="outline">
            <Link href="/admin/weekly-schedule">
              <Repeat className="mr-2 h-5 w-5" />
              Haftalık Planlama
            </Link>
          </Button>
        </div>
      </div>
      
      <div className="bg-blue-50 border-l-4 border-blue-500 text-blue-700 p-4 rounded-md shadow" role="alert">
        <div className="flex items-center">
          <Info className="h-6 w-6 mr-3" />
          <div>
            <p className="font-bold">Otomatik Yayınlama Bilgisi</p>
            <p className="text-sm">Bu sayfa yüklendiğinde veya "Hikaye Kuyruğu" başlığının yanındaki yenile butonuna tıklandığında, yayınlanma zamanı gelmiş "beklemede" olan hikayeler otomatik olarak yayınlanır. Sürekli bir arka plan kontrolü bulunmamaktadır.</p>
          </div>
        </div>
      </div>

      <GenerateStorySection onStoryGenerated={handleStoryGeneratedOrUpdated} />

      <Separator className="my-8" />
      
      <div className="flex items-center mb-4">
        <h2 className="text-2xl md:text-3xl font-semibold text-foreground tracking-tight">
            Hikaye Kuyruğu 
        </h2>
        <Button onClick={() => startRefreshTransition(() => fetchStories(true))} variant="ghost" size="icon" className="ml-2" disabled={isRefreshing || isLoading}>
            <Loader2 className={`h-6 w-6 ${isRefreshing || isLoading ? 'animate-spin' : ''}`} />
        </Button>
      </div>

      <Tabs defaultValue="awaiting_approval" className="w-full">
        <TabsList className="grid w-full grid-cols-3 md:w-auto mb-6">
          <TabsTrigger value="awaiting_approval">
            <ShieldQuestion className="mr-2 h-4 w-4 inline-block" /> Onay Bekleyen ({awaitingApprovalStories.length})
          </TabsTrigger>
          <TabsTrigger value="pending">Bekleyen ({pendingStories.length})</TabsTrigger>
          <TabsTrigger value="published">Yayınlanmış ({publishedStories.length})</TabsTrigger>
        </TabsList>
        <TabsContent value="awaiting_approval">
          {renderStoryList(awaitingApprovalStories, "Onay Bekleyen")}
        </TabsContent>
        <TabsContent value="pending">
          {renderStoryList(pendingStories, "Bekleyen")}
        </TabsContent>
        <TabsContent value="published">
          {renderStoryList(publishedStories, "Yayınlanmış")}
        </TabsContent>
      </Tabs>
    </div>
  );
}
